In [1]:
from datetime import datetime
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

from pylab import mpl
mpl.rcParams['font.sans-serif'] = ['SimHei']

import quantstats

In [3]:
df = pd.read_excel('data/data_tmp.xlsx')
df

,代码,2016-12-30 00:00:00,2017-01-26 00:00:00,2017-02-28 00:00:00,2017-03-31 00:00:00,2017-04-28 00:00:00,2017-05-31 00:00:00,2017-06-30 00:00:00,2017-07-31 00:00:00,2017-08-31 00:00:00,...,2021-02-26 00:00:00,2021-03-31 00:00:00,2021-04-30 00:00:00,2021-05-31 00:00:00,2021-06-30 00:00:00,2021-07-30 00:00:00,2021-08-31 00:00:00,2021-09-30 00:00:00,2021-10-29 00:00:00,2021-11-30 00:00:00
0,000001.SZ,9.10,9.33,9.48,9.17,8.99,9.20,9.39,10.67,11.28,...,21.38,22.01,23.29,24.20,22.62,17.69,17.80,17.93,19.50,17.44
1,000002.SZ,20.55,20.68,20.53,20.58,19.50,21.26,24.97,23.37,23.23,...,33.10,30.00,28.17,26.70,23.81,20.66,19.80,21.31,18.21,18.26
2,000063.SZ,15.95,15.15,15.80,16.96,17.76,19.53,23.74,22.95,23.86,...,31.76,29.32,28.95,31.44,33.23,38.80,33.20,33.13,32.62,30.68
3,000066.SZ,12.44,9.14,10.95,10.10,9.66,8.34,9.01,9.30,8.41,...,17.27,14.86,11.81,15.28,14.60,15.95,14.69,13.19,13.45,14.06
4,000069.SZ,6.95,6.95,7.50,7.30,8.15,8.82,10.06,9.20,8.70,...,8.08,10.19,9.31,8.34,7.44,6.45,6.74,7.49,6.26,5.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,688363.SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,186.07,160.50,154.20,208.50,269.10,277.86,229.01,180.78,185.82,166.00
296,688396.SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,60.09,60.81,55.81,63.50,62.20,91.02,100.00,75.40,68.85,61.78
297,688561.SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,114.99,104.12,88.58,92.91,92.30,92.31,92.46,89.99,81.93,91.51
298,688599.SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.58,20.19,18.55,16.53,18.39,28.35,46.69,60.54,53.56,78.30
299,688981.SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56.18,55.16,54.32,54.68,56.27,61.82,64.69,55.69,55.20,55.04